plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
  - - "@semantic-release-docker"
    - name: blockstack/gh-actions-test
    - registryUrl: quay.io
