plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
  - semantic-release-docker
publish:
  - name: blockstack/gh-actions-test
    registryUrl: quay.io
