plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
  - "@semantic-release/changelog"
  - "@semantic-release/git"
  - - "semantic-release-slack-bot"
    - notifyOnSuccess: true
      notifyOnFail: true
      markdownReleaseNotes: true
