name: main
env:
  IMAGE_NAME: blockstack/gh-actions-test
  DOCKER_REGISTRY: quay.io

on: [push, pull_request]

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Image
        uses: docker/build-push-action@v1
        with:
          repository: ${{ env.IMAGE_NAME }}
          add_git_labels: true
          push: false

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2.5.0
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag and Push Image
        uses: docker/build-push-action@v1
        if: steps.semantic.outputs.new_release_published == 'true'
        with:
          repository: ${{ env.IMAGE_NAME }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
          registry: ${{ env.DOCKER_REGISTRY }}
          tags: ${{ steps.semantic.outputs.new_release_version }}
          tag_with_ref: true
          add_git_labels: true
          push: false
